### ISSUE TITLE
Prep DNR data

### ISSUE THREAD

**Issue by pommevilla** [pommevilla/germs_shiny_project#1]
The DNR data is in 4 different data sets for each of the sample years. Combine all of these Excel files into a single CSV.

There are a different number of columns in each of them. When you combine the data frames, just keep the columns that are common to all years.

## Expected output

* A file named `DNR_all_years.csv` in `data`.

**Comment by jialiu232** [comment]
Created the `DNR_all_years.csv`. I have some doubts for one column `Microcystin`: in df_18, there are "Microcystin Value [ug/L]" and "Microcystin \r\nRAW Value \r\n[ug/L]" columns, while in the rest three data sets, the column name is just `Microcystin`. Should this column be included? If so should we use the "Microcystin Value [ug/L]" or "Microcystin \r\nRAW Value \r\n[ug/L]" column in year 2018 data?

Made a mistake in this task: directly worked on and pushed this change to the main branch, forgot to create a kid branch. My bad, will be more careful later.

**Comment by pommevilla** [comment]
@jialiu232 Microcystin should definitely be in the final merged dataset. Just use `microcystin` as the column name.  

And yes, please be more careful with working on the main branch directly and be sure to work on a development branch next time. :) 

Please make the above change on a new branch and submit a PR. Also, add me as the reviewer when you're ready
