### ISSUE TITLE
Add a plot to the dashboard

### ISSUE THREAD

**Issue by pommevilla** [pommevilla/germs_shiny_project#2]
Currently the Shiny app uses the Iris dataset. Add a plot above the table that only plots the species that is selected in the filter in the sidebar.

## Todo:

- [x] Add `iris_plot` variable to `ui` function in the `dashboardBody`
- [x] Add `iris_plot` output to `server` function (`renderPlot`)

**Comment by jialiu232** [comment]
- Mission accomplished
- Pull request submitted

**Comment by pommevilla** [comment]
Closed by #4
